https://{default}/admin:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: true
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  type: upstream
  upstream: admin:http
  id: admin

https://{default}/api:
  type: upstream
  # the first part should be your project name
  upstream: "api:http"
  id: api

https://{default}/site:
  type: upstream
  # the first part should be your project name
  upstream: "gatsby:http"
  id: gatsby

https://mercure.{default}:
  type: upstream
  upstream: "mercure:http"
  id: mercure
  cache:
    enabled: false
